### ISSUE TITLE
No idea how to run any of the modules.

### ISSUE THREAD

**Issue by Encryption767** [Zylann/SnowfeetEngine#1]
Source built without any problems which is nice. Running the engine is another thing though. The command window pops up with instructions on what to pass but when I do it just throws an error about not finding core mod ect. 
I there a directory structure to this program? Could you provide an example of what to do to run one of the mods?

**Comment by Zylann** [comment]
Maybe the "projects" directory is not well specified.
If you run SnowfeetMain directly, the "-p" argument in the command line must be followed by the relative path to the "projects" directory. So from _bin/debug, a ".." must be added, the commandline should look like this:
-p ../../projects -x samples/rendertest/rendertest.mod.json
It depends on your working directory actually :)

**Comment by Encryption767** [comment]
Thanks for the reply and that cleared things up for me. Runs great.

I was playing around in zcraft earlier and noticed you have a mod for Snowfeet called voxy. Is that a continuation of zcraft in this engine?

**Comment by Zylann** [comment]
Yes, I plan to move all my previous voxel work in that module. I already implemented a few ideas into it, but it's still very work-in-progress and has no sample yet. At the moment I'm focused on the TGUI module because it will be used a lot in the engine's official editor.

**Comment by Encryption767** [comment]
That's good to hear. You plan on making a ToDo list for the TGUI module?

**Comment by Zylann** [comment]
I have a bunch of notes but they are not yet available on Github (and no website yet). Only //TODO in the code at the moment. So yes, I agree there should be a better overview of those tasks/roadmap, at least a .md file for modules :)
